window.esdocSearchIndex = [
  [
    "@becquerel/framework~bq",
    "class/lib/index.js~Bq.html",
    "<span>Bq</span> <span class=\"search-result-import-path\">@becquerel/framework</span>",
    "class"
  ],
  [
    "@becquerel/framework/lib/request.js~request",
    "class/lib/Request.js~Request.html",
    "<span>Request</span> <span class=\"search-result-import-path\">@becquerel/framework/lib/Request.js</span>",
    "class"
  ],
  [
    "@becquerel/framework/lib/response.js~response",
    "class/lib/Response.js~Response.html",
    "<span>Response</span> <span class=\"search-result-import-path\">@becquerel/framework/lib/Response.js</span>",
    "class"
  ],
  [
    "@becquerel/framework/lib/env.js~env",
    "function/index.html#static-function-env",
    "<span>env</span> <span class=\"search-result-import-path\">@becquerel/framework/lib/env.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/request.js",
    "file/lib/Request.js.html",
    "lib/Request.js",
    "file"
  ],
  [
    "lib/request.js~request#accept",
    "class/lib/Request.js~Request.html#instance-member-accept",
    "lib/Request.js~Request#accept",
    "member"
  ],
  [
    "lib/request.js~request#acceptlanguage",
    "class/lib/Request.js~Request.html#instance-member-acceptLanguage",
    "lib/Request.js~Request#acceptLanguage",
    "member"
  ],
  [
    "lib/request.js~request#constructor",
    "class/lib/Request.js~Request.html#instance-constructor-constructor",
    "lib/Request.js~Request#constructor",
    "method"
  ],
  [
    "lib/request.js~request#dnt",
    "class/lib/Request.js~Request.html#instance-member-dnt",
    "lib/Request.js~Request#dnt",
    "member"
  ],
  [
    "lib/request.js~request#headers",
    "class/lib/Request.js~Request.html#instance-member-headers",
    "lib/Request.js~Request#headers",
    "member"
  ],
  [
    "lib/request.js~request#host",
    "class/lib/Request.js~Request.html#instance-member-host",
    "lib/Request.js~Request#host",
    "member"
  ],
  [
    "lib/request.js~request#method",
    "class/lib/Request.js~Request.html#instance-member-method",
    "lib/Request.js~Request#method",
    "member"
  ],
  [
    "lib/request.js~request#path",
    "class/lib/Request.js~Request.html#instance-member-path",
    "lib/Request.js~Request#path",
    "member"
  ],
  [
    "lib/request.js~request#query",
    "class/lib/Request.js~Request.html#instance-member-query",
    "lib/Request.js~Request#query",
    "member"
  ],
  [
    "lib/request.js~request#useragent",
    "class/lib/Request.js~Request.html#instance-member-userAgent",
    "lib/Request.js~Request#userAgent",
    "member"
  ],
  [
    "lib/response.js",
    "file/lib/Response.js.html",
    "lib/Response.js",
    "file"
  ],
  [
    "lib/response.js~response#body",
    "class/lib/Response.js~Response.html#instance-set-body",
    "lib/Response.js~Response#body",
    "member"
  ],
  [
    "lib/response.js~response#body",
    "class/lib/Response.js~Response.html#instance-get-body",
    "lib/Response.js~Response#body",
    "member"
  ],
  [
    "lib/response.js~response#constructor",
    "class/lib/Response.js~Response.html#instance-constructor-constructor",
    "lib/Response.js~Response#constructor",
    "method"
  ],
  [
    "lib/response.js~response#contenttype",
    "class/lib/Response.js~Response.html#instance-get-contentType",
    "lib/Response.js~Response#contentType",
    "member"
  ],
  [
    "lib/response.js~response#contenttype",
    "class/lib/Response.js~Response.html#instance-set-contentType",
    "lib/Response.js~Response#contentType",
    "member"
  ],
  [
    "lib/response.js~response#html",
    "class/lib/Response.js~Response.html#instance-get-html",
    "lib/Response.js~Response#html",
    "member"
  ],
  [
    "lib/response.js~response#html",
    "class/lib/Response.js~Response.html#instance-set-html",
    "lib/Response.js~Response#html",
    "member"
  ],
  [
    "lib/response.js~response#json",
    "class/lib/Response.js~Response.html#instance-set-json",
    "lib/Response.js~Response#json",
    "member"
  ],
  [
    "lib/response.js~response#json",
    "class/lib/Response.js~Response.html#instance-get-json",
    "lib/Response.js~Response#json",
    "member"
  ],
  [
    "lib/response.js~response#send",
    "class/lib/Response.js~Response.html#instance-method-send",
    "lib/Response.js~Response#send",
    "method"
  ],
  [
    "lib/response.js~response#statuscode",
    "class/lib/Response.js~Response.html#instance-set-statusCode",
    "lib/Response.js~Response#statusCode",
    "member"
  ],
  [
    "lib/response.js~response#statuscode",
    "class/lib/Response.js~Response.html#instance-get-statusCode",
    "lib/Response.js~Response#statusCode",
    "member"
  ],
  [
    "lib/response.js~response#text",
    "class/lib/Response.js~Response.html#instance-get-text",
    "lib/Response.js~Response#text",
    "member"
  ],
  [
    "lib/response.js~response#text",
    "class/lib/Response.js~Response.html#instance-set-text",
    "lib/Response.js~Response#text",
    "member"
  ],
  [
    "lib/response.js~response#write",
    "class/lib/Response.js~Response.html#instance-method-write",
    "lib/Response.js~Response#write",
    "method"
  ],
  [
    "lib/env.js",
    "file/lib/env.js.html",
    "lib/env.js",
    "file"
  ],
  [
    "lib/index.js",
    "file/lib/index.js.html",
    "lib/index.js",
    "file"
  ],
  [
    "lib/index.js~bq#constructor",
    "class/lib/index.js~Bq.html#instance-constructor-constructor",
    "lib/index.js~Bq#constructor",
    "method"
  ],
  [
    "lib/index.js~bq#route",
    "class/lib/index.js~Bq.html#instance-method-route",
    "lib/index.js~Bq#route",
    "method"
  ],
  [
    "lib/index.js~bq#routes",
    "class/lib/index.js~Bq.html#instance-member-routes",
    "lib/index.js~Bq#routes",
    "member"
  ],
  [
    "lib/index.js~bq#run",
    "class/lib/index.js~Bq.html#instance-method-run",
    "lib/index.js~Bq#run",
    "method"
  ],
  [
    "lib/index.js~bq#serve",
    "class/lib/index.js~Bq.html#instance-method-serve",
    "lib/index.js~Bq#serve",
    "method"
  ],
  [
    "lib/index.js~bq.route",
    "typedef/index.html#static-typedef-Route",
    "lib/index.js~Bq.Route",
    "typedef"
  ],
  [
    "lib/index.js~bq.routehandler",
    "typedef/index.html#static-typedef-RouteHandler",
    "lib/index.js~Bq.RouteHandler",
    "typedef"
  ]
]